name: Solar System DevSecOps CI

run-name: Solar System CI - ${{ github.event_name }} - ${{ github.ref_name }} # Shows Event name (pull or push) & Branch name that triggerd the Workflow

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - 'feature/*'

  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'

  
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs:

  gitleaks-scan:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  snyk-sca:
    name: Snyk SCA - Dependency Security
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Snyk Dependency Scan
        id: snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: >-
            --severity-threshold=high
            --sarif-file-output=snyk.sarif

      - name: Upload Snyk SARIF to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: snyk-sca

      - name: Enforce Snyk Security Gate 
        if: steps.snyk.outcome == 'failure'
        run: |
          echo "::error::Snyk detected High or Critical dependency vulnerabilities."
          echo "::warning::Build is allowed to continue because these findings are currently accepted/deferred." 
          exit 0
        # exit 1 - if you want to fail the Workflow when Snyk finds High or Critical dependency vulnerabilities

  semgrep-sast:
    name: Semgrep SAST - Static Application Security Testing 
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write # Required to upload SARIF files to GitHub Security tab

    container:
      image: semgrep/semgrep

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run Semgrep SAST
        run: |
          semgrep scan \
            --config auto \
            --sarif --output semgrep.sarif
        # --error returns non zero exit code, when it detects security findings 

      - name: Upload SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          category: semgrep-sast # Keeps it separate from Snyk reports in the Security tab

  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mocha-test-results
          path: test-results.xml
          if-no-files-found: warn # Just to not fail the pipeline, prints warning
          retention-days: 10

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run Code Coverage
        run: npm run coverage

      - name: Archive Coverage Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-results
          path: coverage
          if-no-files-found: warn
          retention-days: 10